### ISSUE TITLE
No origin and destination in mapbox navigation

### ISSUE THREAD

**Issue by dragneel30** [mapbox/mapbox-navigation-android#1307]
When I use 0.13.0 version of navigation-ui there is `NavigationOptions.builder().origin().dest()`
but when I use different version they dont appear in library.

Can someone help me?

**Comment by Guardiola31337** [comment]
Hey @dragneel30 👋 thanks for reaching out and report your question.

I recommend you to use the `NavigationRoute` builder to fetch a route. While it is possible to pass in any `DirectionsRoute` into `MapboxNavigation#startNavigation(DirectionsRoute)`, using this class will ensure your request includes all the proper information needed for the navigation session to begin (including the `origin` and `destination`) 👀 https://www.mapbox.com/android-docs/navigation/overview/#4-requesting-a-route 

I also want to take the opportunity to let you know that we've just released version [`0.19.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.19.0) so I encourage you to upgrade because there are a bunch of improvements and new features plus lots of bug fixes since `0.13.0`.

Hope this helps!

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!

**Comment by dragneel30** [comment]
@Guardiola31337 a lot of tutorials uses 0.18.0 and they still get those methods. anyway thanks. ill try 0.19.0

**Comment by Guardiola31337** [comment]
@dragneel30 awesome! Thanks for the update 👍 

In the future, feel free to report any discrepancies that you might find so we can update our docs, examples and tutorials to be consistent. The team really appreciates the help 🙇

**Comment by dragneel30** [comment]
@Guardiola31337 I didnt really realize that the docs might just be outdated lol anyway thanks too!

**Comment by Guardiola31337** [comment]
Thank you @dragneel30 :pray:
