### ISSUE TITLE
Multiwaypoints using Core and UI SDK

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3345]
We need to verify the behavior of the Core and UI SDK `NavigationView` if a user sets multi waypoints and tries to navigate.

Test Cases to be covered:

Using Core SDK
- [ ] Take a set of 25 waypoints(waypoints should be far from each other maybe like 1 km or more) and navigate
- [ ] Take a set of 25 waypoints(waypoints should be close to each other i.e. the distance should not be more than ~50m b/w the waypoints) and navigate - We are waiting on ANS to give us the route they are following
- [ ] Take a set of 25 waypoints(waypoints should be close to each other i.e. the distance should not be more than ~50m b/w the waypoints) and navigate. Make sure this time you reroute sometimes. We cannot do this using the mock location app. Hence we need the history files. - See [this](https://github.com/mapbox/mapbox-navigation-android/issues/3298#issuecomment-656260459) for the history file attached.

If the above test cases succeed repeat them using `NavigationView`. If not, then we can confirm it's an issue in NavNative and we can close this ticket.

cc @asinghal22 @cafesilencio @zugaldia

**Comment by zugaldia** [comment]
> If the above test cases succeed repeat them using NavigationView.

Are we adding new tests to cover these use cases (preferable), or does this mean manual QA?

**Comment by tkvalentine56** [comment]
[download_waypoints_for_MAPBOX.txt](https://github.com/mapbox/mapbox-navigation-android/files/4932574/download_waypoints_for_MAPBOX.txt)

this is the SQLite row insertion script for the test route I use. Pick and choose 25 points from this list.
It is important that the waypoints stay in sequential order as we have our routes optimized for distance/speed
I test starting at the first waypoint. The on/off route cycling usually happens withing 3-5 points.

**Comment by abhishek1508** [comment]
> Are we adding new tests to cover these use cases (preferable), or does this mean manual QA?

At the moment these are manual QA. We can look into this as to how can these tests be automated, as the use case and requirement is quite unique
cc @zugaldia

**Comment by cafesilencio** [comment]
I tested using the BasicNavigationActivity and the simulator. I used two different routes, one with waypoints more than 1km apart and one with waypoints close together.   During both scenarios the puck just stops part way through. The puck stopped in the same place for each route.   I can see in the log that the routeProgressObserver eventually logs ROUTE_INVALID over and over.   I will include snippets from the log below. I can provide my waypoints if needed.

cc @zugaldia 
cc @asinghal22 

log snippets below:

`26 waypoints more than 1km apart

2020-07-16 15:00:06.515 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: LOCATION_TRACKING
2020-07-16 15:00:06.620 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:06.620 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:07.104 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 0
2020-07-16 15:00:07.125 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 1
2020-07-16 15:00:07.125 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 2, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11666666, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:07.145 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11111111, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:07.522 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970909,-122.525903 hAcc=3 et=?!? vel=26.666666 bear=96.72719 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:07.529 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: LOCATION_TRACKING
2020-07-16 15:00:07.547 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 0
2020-07-16 15:00:07.567 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 2, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11666666, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:07.581 928-989/? D/rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 1
2020-07-16 15:00:07.635 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:07.635 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:07.785 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 1
2020-07-16 15:00:07.791 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 0
2020-07-16 15:00:07.792 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11111111, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:07.802 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 2, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11666666, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:07.871 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 1
2020-07-16 15:00:07.875 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11111111, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:08.524 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970893,-122.525729 hAcc=3 et=?!? vel=23.333334 bear=96.727295 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:08.539 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: LOCATION_TRACKING
2020-07-16 15:00:08.642 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:08.643 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:08.856 1017-1225/? D/ThermalEngine: handle_timer_sig: SS Id SS-SKIN-HIGH-CPU7 Read sdm-therm 43339mC, Err -339mC, SampleCnt 1
2020-07-16 15:00:09.538 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970877,-122.525554 hAcc=3 et=?!? vel=20.0 bear=96.563774 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:09.546 19736-19736/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = ROUTE_COMPLETE
2020-07-16 15:00:09.546 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_COMPLETE
2020-07-16 15:00:09.651 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:09.652 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:10.059 11282-11282/? I/CarrierServices: [2] biu.a: OnCellStateChanged for subId: 2147483647
2020-07-16 15:00:10.539 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970861,-122.525379 hAcc=3 et=?!? vel=16.666666 bear=96.380974 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:10.558 19736-19736/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = OFF_ROUTE
2020-07-16 15:00:10.558 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: OFF_ROUTE
2020-07-16 15:00:10.561 19736-19736/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: onOffRouteStateChanged true
2020-07-16 15:00:10.562 19736-19736/com.mapbox.navigation.examples D/MapboxRerouteController: Fetching route
2020-07-16 15:00:10.639 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970783,-122.524506 hAcc=3 et=?!? vel=0.0 bear=98.09671 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:10.663 19736-19736/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = ROUTE_INVALID
2020-07-16 15:00:10.663 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_INVALID
2020-07-16 15:00:10.667 19736-19736/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: onOffRouteStateChanged false
2020-07-16 15:00:10.667 19736-19736/com.mapbox.navigation.examples D/MapboxRerouteController: Route request interrupted
2020-07-16 15:00:10.669 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:10.670 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:10.672 9692-27068/? E/ResolverController: No valid NAT64 prefix (142, <unspecified>/0)
2020-07-16 15:00:10.675 19736-19736/com.mapbox.navigation.examples D/MapboxRerouteController: Route request canceled
2020-07-16 15:00:10.771 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:10.773 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:00:10.784 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 0
2020-07-16 15:00:10.800 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 2, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11666666, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:11.251 618-618/? I/SDM: HWCDisplay::SetActiveConfig: Active configuration changed to: 1
2020-07-16 15:00:11.255 9779-9807/? I/DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19261132550654593", 1080 x 2280, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1080, height=2280, fps=90.0}, {id=2, width=1080, height=2280, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 440, 442.451 x 445.476 dpi, appVsyncOff 2000000, presDeadline 11111111, touch INTERNAL, rotation 0, type BUILT_IN, address {port=129, model=0x446de5e3a74a}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
2020-07-16 15:00:11.642 19736-19736/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.970780,-122.524483 hAcc=3 et=?!? vel=4.0 bear=97.12756 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:00:11.659 19736-19736/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_INVALID



26 waypoints spaced closely

2020-07-16 15:21:18.797 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: LOCATION_TRACKING
2020-07-16 15:21:18.903 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:18.904 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:19.790 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978534,-122.510041 hAcc=3 et=?!? vel=26.099766 bear=109.311 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:19.796 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: LOCATION_TRACKING
2020-07-16 15:21:19.900 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:19.901 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:20.800 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978523,-122.509896 hAcc=3 et=?!? vel=22.099766 bear=125.307 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:20.806 28746-28746/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = ROUTE_COMPLETE
2020-07-16 15:21:20.807 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_COMPLETE
2020-07-16 15:21:20.913 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:20.915 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:21.804 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978466,-122.509793 hAcc=3 et=?!? vel=19.614925 bear=97.7868 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:21.814 28746-28746/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = OFF_ROUTE
2020-07-16 15:21:21.814 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: OFF_ROUTE
2020-07-16 15:21:21.818 28746-28746/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: onOffRouteStateChanged true
2020-07-16 15:21:21.818 28746-28746/com.mapbox.navigation.examples D/MapboxRerouteController: Fetching route
2020-07-16 15:21:21.903 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978672,-122.508904 hAcc=3 et=?!? vel=0.0 bear=55.81656 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:21.908 28746-28746/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: route progress state = ROUTE_INVALID
2020-07-16 15:21:21.908 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_INVALID
2020-07-16 15:21:21.909 28746-28746/com.mapbox.navigation.examples D/MAPBOX_TELEMETRY: onOffRouteStateChanged false
2020-07-16 15:21:21.910 28746-28746/com.mapbox.navigation.examples D/MapboxRerouteController: Route request interrupted
2020-07-16 15:21:21.920 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:21.921 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:21.935 9692-9277/? E/ResolverController: No valid NAT64 prefix (142, <unspecified>/0)
2020-07-16 15:21:21.936 28746-28746/com.mapbox.navigation.examples D/MapboxRerouteController: Route request canceled
2020-07-16 15:21:22.013 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:22.014 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:22.905 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978682,-122.508885 hAcc=3 et=?!? vel=4.0 bear=60.272118 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:22.912 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_INVALID
2020-07-16 15:21:23.016 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:23.017 10032-10032/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|com.mapbox.navigation.examples|7654|null|10324
2020-07-16 15:21:23.916 28746-28746/com.mapbox.navigation.examples D/NavigationMapboxMap: raw location Location[ReplayRoute 37.978712,-122.508829 hAcc=3 et=?!? vel=8.0 bear=63.820324 vAcc=??? sAcc=??? bAcc=???]
2020-07-16 15:21:23.922 28746-28746/com.mapbox.navigation.examples I/BasicNavigationActivity$routeProgressObserver: route progress: ROUTE_INVALID`

**Comment by asinghal22** [comment]
Team I believe this is a regression in our capabilities. We should fix it ASAP.  

I see this as part of core product functionality described [here](https://docs.mapbox.com/help/how-mapbox-works/directions/):  " requires at least two waypoints — an origin and a destination — but can also include up to 23 additional waypoints between (or a total of 25 waypoints)."

**Comment by abhishek1508** [comment]
@LukasPaczos @Guardiola31337 Based on the testing conducted above, this looks like more of a NavNative issue. It would have made sense if the test with 25 waypoints spaced far from each other working but spaced closer failing. However as seen both the test cases are failing. UI SDK will test it once again when we get a green light from NavNative in regards to fix for the issue.
cc @zugaldia @asinghal22

**Comment by RingerJK** [comment]
I've seen that at both testing RouteStatus is changed not like it should be. Normal behaviour should be like 
```
TACKING -> COMPLETE(means leg has finished) -> TRACKING -> COMPLETE (next leg has finished) -> ... -> COMPLETE
```
But we could observe: 
```
TACKING -> COMPLETE -> (OFF_ROUTE or ROUTE_INVALID) - that is not expected
```
btw I've tested with Native v16.0.0 and didn't observe `ROUTE_INVALID`, but still got `OFF_ROUTE`. 
In case when SDK receives `OFF_ROUTE` it makes a request for a new route so it's ok, when route is reset.
Reported issue to Native team, let's wait for them feedback

**Comment by tkvalentine56** [comment]
I have upgraded to the following components:

        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.7'
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.7'

This issue still exists with the above beta components.

**Comment by zugaldia** [comment]
Thanks @tkvalentine56 for the update - this is a known issue still under investigation by the team. We'll report back here as soon as we have new information.

**Comment by Guardiola31337** [comment]
Where are we here? @RingerJK Could you provide an update when you have a chance? 🙏

**Comment by RingerJK** [comment]
@Guardiola31337 we need a new round of testing with new NavNative version. Can we set it to milestone, otherwise we have a chance lost the issue again?

**Comment by Guardiola31337** [comment]
Where are we here? Any updates? @RingerJK 

cc @Lebedinsky @kmadsen

**Comment by RingerJK** [comment]
@Guardiola31337 let's push it to a sprint 😄 I didn't test that since the last comment here

**Comment by zugaldia** [comment]
Let's re-test in the context of v2 at this point.
