### ISSUE TITLE
Remaining reroute issues

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#374]
Issues discovered during the latest tests:
- [x] The reroute event uses use a timestamp 20s after the original event. The event `created` timestamp should be set to the timestamp of the original reroute rather than the timestamp of when the metrics event was sent. https://github.com/mapbox/mapbox-navigation-android/pull/369#pullrequestreview-68791749 
- [x] The `distanceCompleted` value should represent "the total distance in meters travelled since the start of the navigation session (across all route updates)". 
- [x] The reroute event uses the location when its sent, not the original reroute location https://github.com/mapbox/mapbox-navigation-android/pull/369#pullrequestreview-68791749
- [x] `locationsBefore` uses locations from the very start of the route. It seems the `locationsBefore` and `locationsAfter` arrays aren't being set correctly on reroutes.
- [x] `locationsAfter` is always empty
- [x] The `locationsBefore` and `locationsAfter` appear to be using snapped locations
- [x] `secondsSinceLastReroute` should be time elapsed from the reroute before the current reroute. Currently these are negative values.
- [x] Occasional crashes ~20s after reroutes
- [x] `locationsBefore` can sometimes be empty. Is this expected?
- [x] `locationsAfter` logic might drop locations or contain locations from before the reroute event: https://github.com/mapbox/mapbox-navigation-android/pull/369#pullrequestreview-68792229
- [x] `locationsBefore` locations are backwards

cc @cammace @zugaldia

**Comment by ericrwolfe** [comment]
@zugaldia @cammace Could this be the issue with snapped locations? https://github.com/mapbox/mapbox-navigation-android/blob/9dbdc7ddf012ddbdaa6060252279e47fd876750a/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java#L58-L59

Looks like this updates the location object in place with the snapped lat/lon rather than making a copy.

**Comment by cammace** [comment]
> secondsSinceLastReroute should be time elapsed from the reroute before the current reroute. Currently these are negative values.

Resolved this issue, I was subtracting the new time from the old time causing negative seconds, reversing fixes.

**Comment by zugaldia** [comment]
> locationsAfter is always empty

This was fixed by https://github.com/mapbox/mapbox-navigation-android/pull/348/commits/027482e6b947ff6b2931e83f1c09c798f02c67d1.

>  The locationsBefore and locationsAfter appear to be using snapped locations

I confirmed this is not the case. Both `locationsBefore` and `locationsAfter` are generated directly from the location engine update on https://github.com/mapbox/mapbox-navigation-android/pull/348/files#diff-7e57c49bef82db11f00cfa982b5e2e07R192.

**Comment by zugaldia** [comment]
>  The reroute event uses use a timestamp 20s after the original event. The event created timestamp should be set to the timestamp of the original reroute rather than the timestamp of when the metrics event was sent. #369 (review)

This is the case with https://github.com/mapbox/mapbox-navigation-android/pull/348. The event is queued app on `rerouteOccurred` and the timestamp is added (`lastRerouteDate(new Date())`). This is different from the time at which the event is sent (`sendRerouteEvent`).

**Comment by ericrwolfe** [comment]
> >  The locationsBefore and locationsAfter appear to be using snapped locations
> 
> I confirmed this is not the case. Both `locationsBefore` and `locationsAfter` are generated directly from the location engine update on https://github.com/mapbox/mapbox-navigation-android/pull/348/files#diff-7e57c49bef82db11f00cfa982b5e2e07R192.

@zugaldia agreed that on first glance the code to only store the raw locations looks correct. 

However, real data shows that the locations have been snapped, so something seems to be modifying the locations after they're added to the location buffer. Have you had a chance to check my hunch in https://github.com/mapbox/mapbox-navigation-android/issues/374#issuecomment-336577610?

**Comment by zugaldia** [comment]
>  locationsBefore uses locations from the very start of the route. It seems the locationsBefore and locationsAfter arrays aren't being set correctly on reroutes.

I could reproduce this. It seems to be related to the implementation of `RingBuffer` (cc: @cammace). We were pushing new elements into it and when we reached its capacity it was discarding any new values. With https://github.com/mapbox/mapbox-navigation-android/pull/348/commits/a3078d9b01d51c17167790ebfcf19d399f48423f I've changed the order new location updates are added and I can now see fresh location in the buffer, as well as non-empty lists for both before and after locations.

https://github.com/mapbox/mapbox-navigation-android/pull/348 is now ready for some 👀 as all issues in OP have been addressed.

**Comment by ericrwolfe** [comment]
Thanks for all of the fixes @cammace and @zugaldia.

https://github.com/mapbox/mapbox-navigation-android/pull/348 was merged before I could review. I added a few comments to the original PR that we should address and test drive before final release.

**Comment by ericrwolfe** [comment]
@cammace @zugaldia changes to the locations before and after look great.

The only two remaining issues I'm seeing are:

### Reroute timestamp
This is still not fixed despite the comment in https://github.com/mapbox/mapbox-navigation-android/issues/374#issuecomment-337013458.

### distanceCompleted
The `distanceCompleted` value should represent "the total distance in meters travelled since the start of the navigation session (across all route updates)". This value should represent `SessionState. previousRouteDistancesCompleted` + `routeProgress.distanceTraveled()` as is done here: https://github.com/mapbox/mapbox-navigation-android/blob/6aeab1eed8ea744644cd5ae95dcfc4d85c38ebc8/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationMetricsWrapper.java#L29

**Comment by cammace** [comment]
>  The distanceCompleted value should represent "the total distance in meters travelled since the start of the navigation session (across all route updates)".

resolved this, was a simple case of not setting the new value correctly. Fix is in https://github.com/mapbox/mapbox-navigation-android/pull/389.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/398 finishes this round of fixes, going ahead and closing and proceeding with the release.
