### ISSUE TITLE
Android Drop-In UI: Maneuver Component -> Upcoming Maneuver List loads with no data & expanded.

### ISSUE THREAD

**Issue by EricGeiler** [mapbox/mapbox-navigation-android#6290]
In attempts to reproduce another issue on video, I think we may have discovered an issue with the loading of maneuver instructions at the time of route generation.

I'm a non-dev posting a potential bug, it can be reproduced via the step noted in this ticket.
Any lat/long coordinates can be used to replicate the issue.
Video of this ticket is provided at the very bottom of this post.

Mobile Platform: Android 10
OS Build: 8A.0.8-13-10.0.0-11.22.00
Hardware: Sonim XP8

implementation 'com.mapbox.navigation:ui-app:2.8.0-beta.2'
implementation 'com.mapbox.navigation:ui-dropin:2.8.0-beta.2'

### Steps to trigger behavior

 1.  Start Nav
 2. sometimes the maneuver banner instructions load in an expanded and blank fashion.
 3.  Seems to reproduce more often if user starts nav as soon as the screen appears, possible the full route reply isn't loaded yet, when the user presses "Play" to start nav.
 4. I have seen this personally about 15 times in the past week of testing... I have not yet been able to replicated every single time.
 5. i've verified that the device has ip connectivity at the time of the req.

### Expected behavior

1. Not this behavior.
2. start nav, maneuver details show in upcoming maneuver, in collapsed mode.
3. upcoming maneuver list within the Maneuver Component imo should not expand unless user action is taken to expand it..
4. only auto expansion / showing imo should be sub maneuver banner or lane  guidance section.

### Actual behavior

See video.

https://user-images.githubusercontent.com/61550186/189183667-335e5e86-21c2-4aa1-ba19-4df39471d92d.mp4

**Comment by abhishek1508** [comment]
@EricGeiler Thanks for reporting this issue. 

It's weird as I haven't seen this even once in our internal development app or examples. The only way the `Maneuvers` can expand is either:
- someone clicks on it
- or, if `maneuverView.updateUpcomingManeuversVisibility(VISIBLE)` is invoked.

@Sridhar261990 can you debug the application to see if any of the above is triggered?

**Comment by Sridhar261990** [comment]
Hi @abhishek1508, As we are using the DropInUi, It looks like I have no control or able to debug the maneuver click or 
maneuverView.updateUpcomingManeuversVisibility(VISIBLE). Please correct me if I am wrong. If there is a way to debug then I can really help you to know the cause of the issue. I had a call with Eric and we have tested together. We started and stopped navigation back to back. The issue appears after we do this for 6 to 8 times. We have just tried this 6 to 8 times to reproduce this issue. We did not click maneuver instructions or anywhere in the map except the start and cancel button.

**Comment by EricGeiler** [comment]
This has happened 4 out of 10 times when attempting to start nav on a single device. (my work device used for testing)  

![image](https://user-images.githubusercontent.com/61550186/189728408-844c01dd-72d2-43be-acad-3f836dccffac.png)
![image](https://user-images.githubusercontent.com/61550186/189728457-5cc7c7f5-5177-4e77-90a6-eca17464c3b2.png)
![image](https://user-images.githubusercontent.com/61550186/189728476-6ee808a2-9caf-48c9-aa44-e83d5f8f42b9.png)
![image](https://user-images.githubusercontent.com/61550186/189728499-76a78cf6-899a-42c7-81b0-8393c5eb005a.png)

**Comment by abhishek1508** [comment]
@EricGeiler @Sridhar261990 Is this still reproducible?

**Comment by abhishek1508** [comment]
That's great news. In that case I am gonna close the ticket. Please feel free to reopen if you see it happening again or come across other steps to reproduce this consistently.

@EricGeiler

**Comment by EricGeiler** [comment]
@abhishek1508 sorry bro, bringing some poor news.... we jumped the gun... problem as re-appeared in 2.8.0rc3 in my testing i started in the last hour.

2 out 7 times in my recent testing.  Seems to be more random.
first 2 image are diff time stamps... 3rd image is what happens if you try and close the blank panel, it populates but still won't close.

![image](https://user-images.githubusercontent.com/61550186/192789988-d853cfd4-f268-49da-b07a-e08ddd2dd979.png)
![image](https://user-images.githubusercontent.com/61550186/192790015-7cdb1beb-437d-4ef2-b4b5-9b1fccf6a200.png)
![image](https://user-images.githubusercontent.com/61550186/192790131-45aafc76-352e-4ecc-a5b5-add53226c195.png)

**Comment by EricGeiler** [comment]
Did some packet analysis, and its does not appear to be a connectivity issue.  I see no issues with the connectivity of the device in question.

**Comment by EricGeiler** [comment]
I will do some extensive testing on 2.9.0 alpha4 or greater when its released, we accidentally reference 2.9.0-alpha3 and ran into the known issue, so I can't confirm at this time if this is also present in 2.9.0 ALPHA builds yet.  I'll keep you posted.

**Comment by tomaszrybakiewicz** [comment]
@EricGeiler While investigating this issue, one of our engineers observed similar behaviour in our test applications.

> ... I found out that it is caused by the app calling setNavigationRoutes again with the same routes after starting a trip. During that second call, NavNative sends a status update with banner instructions, which is ignored by the SDK, because all statuses are ignored while routes are being sent to NavNative. NavNative doesn't send these banner instructions again after that second call (probably because the primary route didn't change). 

The patch of the incorrect behaviour is available in [2.9.0-alpha.4](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.9.0-alpha.4)

Please let us know if this fixes the issue or if further investigation is required.

**Comment by EricGeiler** [comment]
@tomaszrybakiewicz Thanks for the analysis.  We are scheduled to update once @Sridhar261990 is back from leave.  I'm expecting to see a new build on Wed or Thurs, will follow up and confirm is issue is resolved.

**Comment by abhishek1508** [comment]
@EricGeiler @Sridhar261990 Did you get a chance to pull `v2.9.0-alpha.4` and test if the issue get resolved?

**Comment by Sridhar261990** [comment]
Hi @abhishek1508, I have updated version 2.9.0-alpha.4. I need some time to test it. I will test it and let you know.

**Comment by Sridhar261990** [comment]
Hi @abhishek1508, I have not seen the issue again with 2.8.0. I have noticed once small issue in v2.9.0-alpha.4. When I start the navigation by using startActiveGuidancestate, the dropin ui is still showing the overview of the route and when I again tap recenter button, the camera position changes and zooming in to my current location.

**Comment by abhishek1508** [comment]
>Hi @abhishek1508, I have not seen the issue again with 2.8.0.

@Sridhar261990, I had an understanding that this was reproducible some times with `v2.8` release train. Can you please confirm if you actually meant `v2.8.0` or some other version. 

> When I start the navigation by using startActiveGuidancestate
This can be done in 2 different ways via Drop-In UI. 
1. By clicking on the `start active guidance` button in the UI.
2. By invoking the api - `navigationView.api.startActiveGuidance(routes)`

Which of the above are you using?

I am curious to find out why are you using `v2.9.0-alpha.4` and not the latest `v2.9.0-beta.2`

Please close this ticket if this issue is resolved. The issue with camera behavior can be addressed separately.

**Comment by EricGeiler** [comment]
@abhishek1508 Sorry, I've been vacation for the past week, just getting caught up now.  I have NOT experienced this issue with v2.8.0-RELEASE, yet we've done a serious amount of testing / nav starts..... 

However in 2.8.0rc1 abd 2.8.0 rc3 the issue is present.  I've been using 2.8.0-release since a few dats after its release.

I have not verified this issue in 2.9.x  alpha or beta, as I do not yet have a 2.9.0 beta build, its coming today from @Sridhar261990

**Comment by abhishek1508** [comment]
> I have NOT experienced this issue with v2.8.0-RELEASE, yet we've done a serious amount of testing / nav starts.....

Thanks for the update @EricGeiler. Great that it is not an issue for you anymore with `v2.8`. However, I would like to confirm that it works with latest `v2.9-beta.x` builds before we close this ticket. Looking forward for further updates on how the testing goes with `v2.9-beta.x`

**Comment by Sridhar261990** [comment]
@abhishek1508 I have updated v2.9.0-beta.2. We will do some testing and confirm it today.

This can be done in 2 different ways via Drop-In UI.

1. By clicking on the start active guidance button in the UI.
2. By invoking the api - navigationView.api.startActiveGuidance(routes)

Which of the above are you using?

I have used navigationView.api.startActiveGuidance. Anyway I did not see that issue in 2.9.0.

**Comment by abhishek1508** [comment]
> I have used navigationView.api.startActiveGuidance. Anyway I did not see that issue in 2.9.0.

You mean 2.9.0-beta.2?

**Comment by Sridhar261990** [comment]
Yes @abhishek1508 .

**Comment by EricGeiler** [comment]
@abhishek1508  closing this issue now, as I cannot reproduce this issue in 2.9.0-beta.2
